name: Gerar APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Instalando Tudo
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          mkdir -p www
          cp index.html www/
          npx cap init "Meu App" "com.meu.app" --web-dir www
          npx cap add android
          npx cap copy
      - name: Fabricando APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Baixar App
        uses: actions/upload-artifact@v3
        with:
          name: app-pronto
          path: android/app/build/outputs/apk/debug/app-debug.apk
