name: Gerar APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Instalando Ferramentas
        run: |
          npm install
          mkdir -p www
          cp index.html www/
          npx cap add android
          npx cap copy
      - name: Compilando APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Download do APK
        uses: actions/upload-artifact@v3
        with:
          name: app-instalavel
          path: android/app/build/outputs/apk/debug/app-debug.apk
