name: Gerar APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Criando Projeto
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          mkdir -p www
          echo "<html><body><h1>App Pronto</h1></body></html>" > www/index.html
          npx cap init "Meu App" "com.meu.app" --web-dir www
          npx cap add android

      - name: Fabricando APK
        run: |
          npx cap copy
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Download
        uses: actions/upload-artifact@v3
        with:
          name: app-final
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
