name: Gerar APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalando e Criando Projeto
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          mkdir -p www
          if [ ! -f index.html ]; then echo "<html><body><h1>App Instalado</h1></body></html>" > index.html; fi
          cp index.html www/
          npx cap init "Meu App" "com.meu.app" --web-dir www
          npx cap add android

      - name: Gerando APK Final
        run: |
          npx cap copy
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Download do APK
        uses: actions/upload-artifact@v3
        with:
          name: app-instalavel
          path: android/app/build/outputs/apk/debug/app-debug.apk
