name: Gerar APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Instalando Ferramentas
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          mkdir -p www
          cp index.html www/
      - name: Inicializar Projeto Android
        run: |
          npx cap init "Meu App" "com.meuapp.br" --web-dir www
          npx cap add android
      - name: Copiar Codigo
        run: npx cap copy
      - name: Compilando APK Real
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Download do APK
        uses: actions/upload-artifact@v3
        with:
          name: app-final
          path: android/app/build/outputs/apk/debug/app-debug.apk
